image: registry.sindria.org/docker-images/image-builder:latest

stages:
    - build
    - push

before_script:
    - export BLUE='\033[0;34m'
    - export YELLOW='\033[0;33m'
    - export RED='\033[0;31m'
    - export NC='\033[0m' #No Color
    - export NOW=$(date "+%Y-%m-%d_%H-%M-%S")

build:image:
    stage: build
    tags:
        - docker
    only:
        - tags
    script:
        - echo -e "${BLUE}Building image...${NC}"
        - bash build.sh 1000 $CI_COMMIT_TAG 10.2
        - bash build.sh 1000 $CI_COMMIT_TAG 10.4
        - cowsay -f tux "Build Success"

push:image:
    stage: push
    tags:
        - docker
    only:
        - tags
    script:
        - echo -e "${BLUE}Pushing image into registry...${NC}"
        - docker push sindriainc/mariadb:$CI_COMMIT_TAG-10.2
        - docker push sindriainc/mariadb:$CI_COMMIT_TAG-10.4
        - docker push sindriainc/mariadb:latest
        - echo #
        - echo -e "${BLUE}Cleaning local registry...${NC}"
        - docker image rm sindriainc/mariadb:$CI_COMMIT_TAG-10.2
        - docker image rm sindriainc/mariadb:$CI_COMMIT_TAG-10.4
        - docker image rm sindriainc/mariadb:latest
        - echo #
        - cowsay -f dragon "Well Done! New docker image is now on your registry."

